samples: add missing CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y to all new samples
CJSON_LIB depends on (NEWLIB_LIBC && NEWLIB_LIBC_FLOAT_PRINTF). All 8
new sample prj.conf files had CONFIG_NEWLIB_LIBC=y but were missing
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y, causing Kconfig to abort with:
  error: Aborting due to Kconfig warnings